# Settings
gems: [jekyll-paginate]
permalink:           pretty
baseurl:             https://cycade.github.io
paginate:            5
encoding:            utf-8

version:             1.0.0
title:               Cycade's Blog
tagline:             Rauschen der Wind

# About/contact
author:
  name:              Li Chenqiang
  email:             inahocyc@gmail.com
  githubAddress:     https://github.com/Cycade
  # avater:

excerpt_separator:   <!--more-->
