title: 如何一本正经的瞎扯
description: Cycade's Blog
author: Cycade
github: https://github.com/cycade
about: 半路出家，是个弱鸡，精通自黑，能写JS。
disqus_shortname: stackproblems

enableTags: true
tagarray: []

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/profile.php?id=100009483876282"
    - icon: fa-github
      link: "https://github.com/cycade"

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://cycade.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
